export const DEFAULT_REFRESH_TOKEN_COOKIE_NAME = 'gestion_stagiaire_refresh';
export const DEFAULT_ACCESS_TOKEN_TTL_SECONDS = 900;
export const DEFAULT_REFRESH_TOKEN_TTL_SECONDS = 7 * 24 * 60 * 60;
export const REFRESH_TOKEN_INVALID_CODE = 'REFRESH_TOKEN_INVALID_OR_EXPIRED';
